// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBee7BqTqKLuQ1lCqPblm6rcL2Z1kwvmN4',
    appId: '1:548720142157:web:28e4b78f1bfa2c7d76f904',
    messagingSenderId: '548720142157',
    projectId: 'chatapp-3a898',
    authDomain: 'chatapp-3a898.firebaseapp.com',
    storageBucket: 'chatapp-3a898.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzS_-lUhOqbxt_KxDZBVk-6S2qMlZA0ss',
    appId: '1:548720142157:android:0bda617bc545b86776f904',
    messagingSenderId: '548720142157',
    projectId: 'chatapp-3a898',
    storageBucket: 'chatapp-3a898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDeY17f6ogko31vvSObV88bIeUIBPj18',
    appId: '1:548720142157:ios:92022ef3cb0cf2bf76f904',
    messagingSenderId: '548720142157',
    projectId: 'chatapp-3a898',
    storageBucket: 'chatapp-3a898.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

}